services:
  jupyter:
    privileged: true
    image: tf-ml
    ports: 
    - "8080:8888"
    volumes:
      - ./:/home/jupyteruser/
    environment:
      - JUPYTER_TOKEN=f9a3bd4e9f2c3be01cd629154cfb224c2703181e050254b5
      - DISPLAY
    devices:
      - "/dev/bus/usb/002/001:/dev/video0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
